// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineCompilerWebApplication.Models;

#nullable disable

namespace OnlineCompilerWebApplication.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OnlineCompilerWebApplication.Models.Student", b =>
                {
                    b.Property<Guid>("FacultyNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AcademicDegreeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AcademicDegreeType")
                        .HasColumnType("int");

                    b.Property<short>("Course")
                        .HasColumnType("smallint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("Group")
                        .HasColumnType("smallint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("Semester")
                        .HasColumnType("smallint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<short>("Stream")
                        .HasColumnType("smallint");

                    b.Property<int>("StudyType")
                        .HasColumnType("int");

                    b.HasKey("FacultyNumber");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
